kind: Pod
apiVersion: v1
metadata:
  name: podwithsecvol
spec:
  volumes:
  - name: secvol
    secret:
      secretName: myfirstsecret
  containers:
  - name: container1
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: secvol
      mountPath: /secretdata
