kind: Pod
apiVersion: v1
metadata:
  name: podwithcmvol
spec:
  volumes:
  - name: cmvol
    configMap:
      name: myfirstcm
  containers:
  - name: container1
    image: nginx
    volumeMounts:
    - name: cmvol
      mountPath: /data/cm
    imagePullPolicy: IfNotPresent
