apiVersion: v1
kind: Pod
metadata:
  name: rp-http-fail
spec:
  containers:
  - name: container-rp
    image: aamirpinger/helloworld:latest
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        port: 90
        path: /
